# Generated by Django 5.1.4 on 2025-07-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=14)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
